### ISSUE TITLE
Red bar shoing when CMS fields left blank

### ISSUE THREAD

**Issue by yblock** [openstax/os-webview#1953] opened 2021-02-03 17:45 UTC
When the  "Community resource feature link" / " Community resource feature text" fields are not populate in the CMS, a red bar is displaying at the bottom of the card:

![Screen Shot 2021-02-03 at 11.42.01 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/bd482893-97c6-4367-970c-d9045e67c6e1)

Here is an example of what it looks like when the fields are populated with content:
![Screen Shot 2021-02-03 at 11.44.54 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/eba2cf9e-cf35-44b7-9bf8-47a46f6155af)

**Comment by mwharrison** [comment] 2021-02-03 18:24
@yblock this is a duplicate of: https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/os-webview/1945

Closing this in favor of that card - but that's for reporting! :)

**Closed by mwharrison** 2021-02-03 18:24 UTC
Labels: bug
